# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # HydePHP 3.x
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[3.x] "
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[3.x] "
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "packages/hyde"
      - "packages/hydefront"
    target-branch: "master"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[3.x] "
    groups:
      frontend-deps:
        patterns:
          - "vite"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # HydePHP 2.x
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[2.x] "
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[2.x] "
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "packages/hyde"
      - "packages/hydefront"
    target-branch: "2.x"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[2.x] "
    groups:
      frontend-deps:
        patterns:
          - "vite"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
