<?php

declare(strict_types=1);

namespace Hyde\Framework\Features\XmlGenerators;

use Hyde\Pages\InMemoryPage;

use function app;

/**
 * @internal This page is used to render the RSS feed for the site.
 *
 * The contents are generated by the RssFeedGenerator, which is resolved from the
 * service container when the page is compiled, so the output can be customized
 * by rebinding the generator class in the container.
 */
class RssFeedPage extends InMemoryPage
{
    public function __construct()
    {
        parent::__construct(static::routeKey(), [
            'navigation' => ['hidden' => true],
        ]);
    }

    public function compile(): string
    {
        return app(RssFeedGenerator::class)->generate()->getXml();
    }

    /**
     * Get the route key of the RSS feed, which for this page is also its output path.
     */
    public static function routeKey(): string
    {
        return RssFeedGenerator::getFilename();
    }

    /**
     * The identifier is the user-configured `hyde.rss.filename` and is always used
     * verbatim as the output path, regardless of its extension, so filenames like
     * `feed.rss` outside the default recognized extensions keep working.
     */
    protected static function identifierHasExplicitOutputExtension(string $identifier): bool
    {
        return true;
    }
}
