<?php

declare(strict_types=1);

namespace Hyde\Framework\Features\XmlGenerators;

use Hyde\Pages\InMemoryPage;

use function app;

/**
 * @internal This page is used to render the sitemap for the site.
 *
 * The contents are generated by the SitemapGenerator, which is resolved from the
 * service container when the page is compiled, so the output can be customized
 * by rebinding the generator class in the container.
 */
class SitemapPage extends InMemoryPage
{
    public function __construct()
    {
        parent::__construct(static::routeKey(), [
            'navigation' => ['hidden' => true],
        ], exactOutputPath: true);
    }

    public function compile(): string
    {
        return app(SitemapGenerator::class)->generate()->getXml();
    }

    /**
     * Get the route key of the sitemap, which for this page is also its output path.
     */
    public static function routeKey(): string
    {
        return 'sitemap.xml';
    }
}
