<?php

declare(strict_types=1);

namespace Hyde\Framework\Features\GeneratedFiles;

use Hyde\Facades\Features;
use Hyde\Framework\Features\TextGenerators\LlmsTxtGenerator;
use Hyde\Framework\Features\TextGenerators\RobotsTxtGenerator;
use Hyde\Framework\Features\XmlGenerators\RssFeedGenerator;
use Hyde\Framework\Features\XmlGenerators\SitemapGenerator;

use function array_filter;
use function array_values;

/**
 * @internal Registry of files generated by the core extension.
 */
final class GeneratedFileRegistry
{
    public const SITEMAP = 'sitemap.xml';
    public const ROBOTS = 'robots.txt';
    public const LLMS = 'llms.txt';

    /** @return array<\Hyde\Framework\Features\GeneratedFiles\GeneratedFilePage> */
    public static function pages(): array
    {
        return array_values(array_filter([
            Features::hasSitemap() ? new GeneratedFilePage(self::SITEMAP, SitemapGenerator::class) : null,
            Features::hasRss() ? new GeneratedFilePage(self::rssOutputPath(), RssFeedGenerator::class) : null,
            Features::hasRobotsTxt() ? new GeneratedFilePage(self::ROBOTS, RobotsTxtGenerator::class) : null,
            Features::hasLlmsTxt() ? new GeneratedFilePage(self::LLMS, LlmsTxtGenerator::class) : null,
        ]));
    }

    public static function rssOutputPath(): string
    {
        return RssFeedGenerator::getFilename();
    }
}
