<?php

declare(strict_types=1);

namespace Hyde\Framework\Features\TextGenerators;

use Hyde\Pages\InMemoryPage;

use function app;

/**
 * @internal This page is used to render the robots.txt file for the site.
 *
 * The contents are generated by the RobotsTxtGenerator, which is resolved from the
 * service container when the page is compiled, so the output can be customized
 * by rebinding the generator class in the container.
 */
class RobotsTxtPage extends InMemoryPage
{
    public function __construct()
    {
        parent::__construct(static::routeKey(), [
            'navigation' => ['hidden' => true],
        ], exactOutputPath: true);
    }

    public function compile(): string
    {
        return app(RobotsTxtGenerator::class)->generate();
    }

    /**
     * Get the route key of the robots.txt file, which for this page is also its output path.
     */
    public static function routeKey(): string
    {
        return 'robots.txt';
    }
}
